version: "3"

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - my_network

  app-nodejs:
    build: ./containers/nodejs/
    container_name: app-nodejs
    depends_on:
      - db-mongo
    expose:
      - "3000"
    environment:
      MONGO_URI: mongodb://db-mongo:27017/mydb
      VIRTUAL_HOST: "somedomain.local"
      VIRTUAL_PORT: "3000"
    networks:
      - my_network

  db-mongo:
    image: mongo
    container_name: db-mongo
    restart: always
    expose: 
      - "27017"
    volumes:
      - data:/data/db
    networks:
      - my_network

volumes:
  data:

networks:
  my_network:
    driver: bridge